---
  - hosts: localhost
    vars_files:
      - host_vars/vms/vault.yml
    roles:
      - createvm
    post_tasks:
      - name: Refresh inventory to ensure new instances are recognized
        meta: refresh_inventory

  - import_playbook: ssh.yml

  - hosts: web
    become: true
    roles:
      - nginx

  - hosts: db
    become: true
    roles:
      - mariadb

  - hosts: client
    become: true
    roles:
      - client
