---
  - hosts: localhost
    vars_files:
      - host_vars/vms/vault.yml
    roles:
      - createvm

  - hosts: web
    become: true
    roles:
      - nginx

  - hosts: db
    become: true
    roles:
      - mariadb

  - hosts: client
    become: true
    roles:
      - client
